appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: aF78smf1DwF1EZKVW5uJrSEkOYDaWv+1rmmRXUaoOZ+DDytNIw6EoOEGOqyvQ5QRkU9xuxluY3c8r09aS4wHM7Lvn8LF9InXbpQqKiOd/Sac9mBiFLuoiWWVI3wP2JMivdNYUhfkMaW51VmGAoqGqn4O8+N9/cuP5hK177yrs54+XXqQy7LL62a8Rd/BEyHZ0qCDh4FFB/eQDfmGIVU81FAUepU7yXhkRN4Nrtn+F++i3+sqifuVgqNs74M5iQO8uA37ODVUBMuKjztAILy4TMfgJRc909619AV9+6PEJIBNF2u+maiGN0xuoTcZoSXLJrxGc1A56xs2WTLmuPcVRtSJXW4UleRRTnKdQ1xUrNIFYueokwRcafV3q93pQvPf1QVRam0CdXqEI3On6fWBqyvRpdjv0t/kxQ/uw9gb8ayqmcSLN5g3PeoZZLJeIprDQAHn+PLd8k3EF9JjdHDis0eRksG1MQfkESBlsG/G5kgDnMa5TrZKQPO6tyA+wX3D3FpsWiE/2rOhQgYzcVHK0LnPYyqGD7FikxhLW1TGGdwXWQbeHDA0gjwjrqDyxAZPY8mD8KM9Z0+GA9Hs+39dHxXjSDt7JtK9d4RUnC7FlvvlPKVXF0sf7GbO4pd3fH6ve0jMGT9YNjoL/R6uNkxYgKaH20V3RZSnQvpR04dCkJ8=
